apiVersion: v1
kind: ConfigMap
metadata:
  # This name is referenced by your deployment files.
  name: app-config
data:
  # --- Frontend Configuration ---
  # The URL the React app will use to contact the backend inside the cluster.
  REACT_APP_API_URL: "/api"

  # --- Backend Configuration ---
  # Set Django's debug mode. Should be "False" for production.
  DJANGO_DEBUG: "True"
  
  # A comma-separated list of allowed hostnames for Django.
  # Using '*' is convenient for a first deployment but not secure for production.
  DJANGO_ALLOWED_HOSTS: "*"
  
  # A comma-separated list of origins allowed to make cross-site requests.
  # This should be the external URL of your frontend.
  CORS_ALLOWED_ORIGINS: "*"