apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterInterceptor
metadata:
  name: github
spec:
  clientConfig:
    service:
      name: tekton-triggers-webhook
      namespace: tekton-pipelines
      path: /interceptors/github
---
apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterInterceptor
metadata:
  name: gitlab
spec:
  clientConfig:
    service:
      name: tekton-triggers-webhook
      namespace: tekton-pipelines
      path: /interceptors/gitlab
---
apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterInterceptor
metadata:
  name: bitbucket
spec:
  clientConfig:
    service:
      name: tekton-triggers-webhook
      namespace: tekton-pipelines
      path: /interceptors/bitbucket
---
apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterInterceptor
metadata:
  name: cel
spec:
  clientConfig:
    service:
      name: tekton-triggers-webhook
      namespace: tekton-pipelines
      path: /interceptors/cel
