SUCCESS = "successMSG"
ERROR = "errorMSG"
OPERATION_SUCCESS = "Operation successful"
OPERATION_FAILED = "Operation failed"
PDF_UPDATED_SUCCESSFULLY = "PDF updated successfully"
PDF_DELETED_SUCCESSFULLY="PDF deleted Successfully"
ANALYSIS_NOT_COMPLETED="Analysis not completed yet"
PDF_NOT_FOUND="PDF document with this pk not found"